---
title: " "
---

<br>
<br>
<br>
<br>



Kolegij *Multivarijatne metode* je namijenjen sociolozima na diplomskoj razini koji su upoznati sa teoretskim osnovama statistike i praktičnom primjenom univarijatnih metoda deskriptivne i inferencijalne statistike, a koristan može biti i studentima iz drugih društvenih i humanističkih zananosti. Fokus kolegija je na razumijevanju osnovnih multivarijatnih metoda i njihovoj praktičnoj primjeni na modernim podatcima (web, društvene mreže, mobilne aplikacije, senzorni uređaji).

Kolegij polazi od **Data Science** pristupa društvenim znanostima i integrira standardne alate eksplorativne i konfirmatorne statističke analize u sintaksu programskog jezika R. Predznanje programskog jezika R nije nužno ali se preporuča. Pored razumijevanja i provođenja multivarijatne (naprdene) statističke analize, u kolegiju će se obrađivati i niz popratnih informatičkih tehnologija poput: markdown jezika (*RMarkdown*), platformi za suradnju razmjenu koda (*Git*, *GitHub*), vizualizacije podataka (*Tableau*, *ggplot2*), podrške za manipulaciju podatcima (*tidyverse*, *data.table*), preuzimanja podataka (*web scraping*, *API*) i rada sa bazama podataka (*SQL*,*Google Big Querry*).


Kolegij nije zamišljen kao sveobuhvatna referenca za rad s *Big Data* tehnologijama u društvenim znanostima jer materijali ne pokrivaju: rad sa terminalom (*Bash Shell*), rad sa platformama za suradnju i razmjenu koda (*Git*, *GitHub*), rad sa *Docker*-om, programiranje i iteraciju, paralelno programiranje, rad u oblaku (*Cloud*), ostale programske jezike (*Python*, *Java*, *HTML*, *Scala*). 

Cilj kolegija je upoznavanje sa:

1) Standardnim eksplorativnim i konfirmatornim multivarijatnim metodama 
2) Alatima za obradu i manipulaciju podataka 
3) Modernom metodologijom za analizu podataka 
4) Alatima za prezentaciju i dijeljenje rezulata 
5) Programskim jezikom R


<br>

Kolegij će osposobiti studente za razumijevanje i provedbu napredne statističke analize, te omogućiti uključivanje u modernu analitičku paradigmu (*computational social science*) i tehnološke (*frontier*) tokove u obradi podataka (*data science*). Osim naglaska na akademsku primjenu stečenog znanja, kroz kolegij će se studentima olakšati uključivanje u poslovni IT sektor na strani analitike.


<br>

### Literatura

Koristiti ćemo mnoštvo različitih knjiga i resursa koje će biti dostupne na linkovima kod svakog predavanja.

Sljedeće knjige ulaze u literaturu za kolegij:

- [Udžbenik](http://www.alinea.hr/105.html) iz multivarijatnih statističkih metoda na hrvatskom jeziku.

- [Uvodni udžbenik](https://link.springer.com/book/10.1007/978-1-4419-9650-3) za multivarijatne metode u R.

- [Udžbenik](https://github.com/gabi493/ADEI/blob/master/Husson%20F.%20et%20al.%20-%20Exploratory%20Multivariate%20Analysis%20by%20Example%20-%20Using%20R%20-%202011.pdf) iz eksplorativne multivarijatne analize u R.

- [Detaljni udžbenik](https://www.springer.com/gp/book/9783642360046) za multivarijatnu statistiku.

- [Sveobuhvatni udžbenik](https://us.sagepub.com/en-us/nam/using-r-with-multivariate-statistics/book243861#contents) za multivarijatnu statistiku u R.

- [Tehnički udžbenik](https://web.uniroma1.it/memotef/sites/default/files/file%20lezioni/102b_textbook.pdf) za multivarijatne metode u R.

- Za pregled modernog pristupa društvenim znanostima na osnovi podataka: [Bit by Bit: Social Research in the Digital Age](https://www.bitbybitbook.com/en/1st-ed/preface/).

- Ovo je klasična literatura za [R](https://r4ds.had.co.nz/).

<br>

