---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, PBC"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/be/Sharingan_triple.svg)

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```



```{r libs, include=TRUE, echo=FALSE,message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(here)
library(kableExtra)
library(DT)
```


# CLASS OUTLINE
<br>
<br>
- DATA OVERVIEW
<br>
<br>
- FACEBOOK
<br>
<br>
- WEB
<br>
<br>
- TWITTER
<br>
<br>
- YOUTUBE
<br>
<br>
- FORUM
<br>
<br>
- INSTAGRAM
<br>
<br>

---
layout: true
# DATA OVERVIEW
---

- check the raw [data](https://github.com/lusiki/Learning-Social-Media-Analytics/blob/main/data/Mediatoolkit/sample.xlsx)
- sourced from [Mediatoolkit](https://www.mediatoolkit.com/)



```{r, echo=F}
# read data in (one day worth of data)
one_day_sample <- read_excel(here::here("data/Mediatoolkit/sample.xlsx"))
# size of the data
dim(one_day_sample)
# sneek peak
glimpse(one_day_sample[sample(nrow(one_day_sample)),1:35])

```

---
<br>
<br>
