---
title: " "
---

<br>
<br>
<br>
<br>


## R 

<ul>
<li><a href="https://education.rstudio.com/learn/">RStudio: Finding Your Way To R</a></li>
<li><a href="https://www.datacamp.com/courses/free-introduction-to-r">DataCamp's Introduction to R</a></li>
<li><a href="http://adv-r.had.co.nz/">Advanced R</a></li>
<li><a href="https://www.r-bloggers.com/">R bloggers</a></li>
<li><a href="https://cran.r-project.org/web/views/Multivariate.html">CRAN Task View: Multivariate Statistics</a></li>
<li><a href="https://cran.r-project.org/web/views/SocialSciences.html">CRAN Task View: Statistics for the Social Science</a></li
</ul>


## Open Source repozitoriji iz multivarijatne statistike


<ul>
<li><a href="https://github.com/nthun/courses-multivariate-statistics-in-R-2018-fall">Github repozitorij (kolegij) iz multivarijatne statistike</a></li>
<li><a href="https://people.stat.sc.edu/Hitchcock/stat530.html">Applied Multivariate Statistics and Data Mining</a></li>
</ul>



## Online predavanja iz multivarijatnih metoda 

<ul>
<li><a href="https://www.udemy.com/course/applied-multivariate-analysis-with-r/?utm_source=adwords&utm_medium=udemyads&utm_campaign=LongTail_la.EN_cc.ROW&utm_content=deal4584&utm_term=_._ag_77879424214_._ad_437497333845_._kw__._de_c_._dm__._pl__._ti_dsa-1007766171552_._li_20229_._pd__._&matchtype=b&gclid=Cj0KCQiAvbiBBhD-ARIsAGM48bwurNZTDDJ71ffigbknOBbdua2-BA57vUG0O7qSHJlK5QBm-RkIxmsaAsqjEALw_wcB">Izvrstan Udemy tečaj iz Multivarijatne statistike</a></li>
</ul>





## Online knjige


<ul>
<li><a href="https://bookdown.org/brian_nguyen0305/Multivariate_Statistical_Analysis_with_R">Bookdown: Multivariate Statistical Analysis with R </a></li>
</ul>



## Statistička beletristika

<ul>
<li><a href="https://www.pdfdrive.com/penguin-books-how-to-lie-with-statistics-darrell-huff-e119748826.html">How to lie with statistics</a></li>
<li><a href="https://www.bookdepository.com/Art-Statistics-David-Spiegelhalter/9780241258767?pdg=dsa-19959388920:cmp-8862937091:adg-86528077382:crv-411135277650:pos-:dev-c&gclid=CjwKCAjwiOv7BRBREiwAXHbv3LXBoXSa-a8cNTrV3aewUF0MkjMZRiknrYma4gIeWYxwf4eiV9obQBoC2EAQAvD_BwEl">The Art of Statistics: Learning from Data</a></li>
<li><a href="https://www.amazon.com/How-Make-World-Add-Up/dp/1408712245">How-Make-World-Add-Up</a></li>
<ul>




## Srodni kolegiji


<ul>
<li><a href="http://modelingsocialdata.org/">Modeling Social Data</a></li>
<li><a href="http://www.princeton.edu/~mjs3/soc504_s2015/#">Advanced data analysis for the social sciences</a></li>
<ul>


## Computational social science



<ul>
<li><a href="https://msalganik.wordpress.com/">Blog od Matthew Salganik-a</a></li>
<li><a href="http://www.princeton.edu/~mjs3/">Osobni web od Matthew Salganik-a</a></li>
<li><a href="https://sicss.io/">Ljetni CSS instituti</a></li>
<li><a href="http://pablobarbera.com/POIR613/index.html">Izvrstan CSS kolegij</a></li>

<ul>


## Ostalo

<ul>
<li><a href="https://towardsdatascience.com/best-data-science-blogs-to-follow-in-2020-d03044169eb4">Data science blogovi</a></li>
<li><a href="https://towardsdatascience.com/data-science-books-you-should-read-in-2020-358f70e1d9b2">Data science knjige</a></li>
<li><a href="https://srdas.github.io/Papers/DSA_Book.pdf">Izvrsna knjiga iz Podatkovnih znaosti</a></li>
<li><a href="https://nealcaren.github.io/python-tutorials/">Izvrstan online tečaj iz Pythona za društvene znanosti</a></li>
<li><a href="https://lusiki.github.io/WebStatistika/">Kolegij iz Primjenjene statistike</a></li>
<li><a href="https://lusiki.github.io/WebObradaPodataka/">Kolegij iz Obrade podataka</a></li>
<li><a href="https://rpubs.com/shichich">Prošlogodišnja predavanja</a></li>
<ul>



<br>
<br>
<br>

