---
title: " "
---
 
<br>
<br>
<br>
<br>

*Napomena*: .html i .Rmd formati predavanja su dostupni u [repozitoriju](https://github.com/lusiki/WebMultiVar).
<br>

### Predavanje 01: Pregled kolegija i studentskih obveza


- Uvod u kolegij
- Struktura, obveze i ciljevi
- Rasprava: *Računalne društvene znanosti (CSS)*

<br>
**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/01_UVOD.html) | [.rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/01_UVOD.Rmd)
<br>
**Čitanje:**  [Manifesto za računalne društvene znanosti](http://www.everyaware.eu/resources/publications/Conte-2012.pdf)
<br>
<br>

### Predavanje 02: Osnove programskog jezika R

- Instalacija
- Zašto R?
- Osnovni koncepti
- Objektno orjentirano programiranje u R
- "Sve je objekt"
- "Sve ima naziv"
- Indeksiranje
- Čišćenje radnog prostora

<br>
**Dodatak predavanju:**[Vizualizacijski sustav ggplot2](https://raw.githack.com/lusiki/WebMultiVar/main/Predavanja/02_UVOD-U-R_dodatak.html#1) | [Uvod u R *(Primijenjena statistika)*](https://raw.githack.com/BrbanMiro/WebStatistika/main/Moduli/02_UVOD_U_R_xar.html#1) | [Dodatni R koncepti *(Primijenjena statistika)*](https://raw.githack.com/BrbanMiro/WebStatistika/main/Moduli/02_DODATNI_KONCEPTI_R_xar.html#1)
<br>
**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/02_UVOD-U-R.html) | [.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/02_UVOD%20U%20R.Rmd) + (*dodatak:* [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/02_UVOD%20U%20R_dodatak.Rmd)|[.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/02_UVOD-U-R_dodatak.html) )
<br>
**Čitanje:** [Upoznavanje sa sintaksom jezika R](https://www.srce.unizg.hr/files/srce/docs/edu/R/s720_polaznik.pdf) + [Uvod u korištenje R-a](https://cran.r-project.org/doc/contrib/Kasum+Legovic-UvodUr.pdf)
<br>
<br>

### Predavanje 03: Osnove deskriptivne i infencijalne statistike

<br>

##### **Deskriptivna statistika**

- Mjere centralne tendencije
- Mjere varijabilnosti
- Varijable i podatkovni okviri
- Standardizirane vrijednosti
- Korelacija

**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/03_PONAVLJANJE-DESKRIPTIVNA.html) | [.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/03_PONAVLJANJE%20DESKRIPTIVNA.Rmd) 
<br>
**Čitanje:** [Skripta iz deskriptivne statistike](http://matematika.fkit.hr/novo/statistika_i_vjerojatnost/predavanja/1%20-%20Deskriptivna%20statistika.pdf) + [Deskriptivna statistika u R](https://rcompanion.org/handbook/C_02.html)
<br>
<br>


##### **Inferencijalna statistika**

- Pretpostavke statističkih testova
- Normalnost distribucije
- Testovi korelacije
- Testovi za usporedbu prosjeka
- Testovi za usporedbu varijance
- Testovi za usporedbu kategorija
- Linearna regresija
- Višestruka linearna regresija

**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/03_PONAVLJANJE-INFERENCIJALNA.html) | [.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/03_PONAVLJANJE%20DESKRIPTIVNA.Rmd) 
<br>
**Čitanje:** [simpleR viggnete](https://cran.r-project.org/doc/contrib/Verzani-SimpleR.pdf)
<br>
<br>


### Predavanje 04: Analiza glavnih komponenti (PCA)

- Definicija PCA
- Primjeri 
- PCA u praktičnoj primjeni


**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/04_PCA.html) | [.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/04_PCA.Rmd) 
<br>
**Čitanje:** [Blog post](https://towardsdatascience.com/learn-principle-component-analysis-in-r-ddba7c9b1064) + [Tehničko poglavlje u knjizi](http://staff.ustc.edu.cn/~zwp/teach/MVA/abdi-awPCA2010.pdf)
<br>
<br>

### Predavanje 05: Faktorska analiza

- Jednodimenzionalna faktorska analiza (FA)

- Multidimenzionalna FA

- Konfirmatorna FA


**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/05_FA.html) | [.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/05_FA.Rmd) 
<br>
**Čitanje:** <a href="./Foto/Faktorska_analiza.pdf">Faktorska analiza (teorija)</a> + [Faktorska analiza (praktično;lavaan paket)](https://stats.idre.ucla.edu/r/seminars/rcfa/#s3)
<br>
<br>

### Predavanje 06: Klaster analiza

- Karakteristike klaster analize

- Udaljenost između opservacija

- Hijerarhijski klastering

- K-means klastering


**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/06_KLASTER.html) | [.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/06_KLASTER.Rmd) 
<br>
**Čitanje:** [Msc rad koji koristi Klaster analizu](https://zir.nsk.hr/islandora/object/pmf%3A9063/datastream/PDF/view) + [Predavanje iz prošle godine](https://rpubs.com/shichich/595542) + [Knjiga iz klaster analize u R](https://xsliulab.github.io/Workshop/week10/r-cluster-book.pdf)
<br>
<br>


### Predavanje 07: Multivarijatna regresijska analiza

- Praktični primjer

- Univarijatna regresijska analiza

- Predikcija i elementi modela

- Kvaliteta procjene

- Višestruka regresija


**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/07_REG.html) | [.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/07_REG.Rmd) 
<br>
**Čitanje:** []() + [Predavanje iz Primjenjene statistike godine](https://raw.githack.com/lusiki/WebStatistika/main/Moduli/11_REG.html) + []()
<br>
<br>

### Predavanje 08: Analiza sadržaja 

- Praktični primjer

- Univarijatna regresijska analiza

- Predikcija i elementi modela

- Kvaliteta procjene

- Višestruka regresija


**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/08_TXT.html) | [.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/08_TXT.Rmd) 
<br>
**Čitanje:** [Prošlogodišnje predavanje](https://rpubs.com/shichich/605152) + [Text Mining with R](https://www.tidytextmining.com/) + [Tidytext tutorial na learnr platformi](https://juliasilge.com/blog/learn-tidytext-learnr/)
<br>
<br>

### Predavanje 09: Survival analiza

- Karakteristike survival analize

- Procjena survival krivulja

- Weibull model

- Cox model

**Format predavanja:** [.html](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/09_SURV.html) | [.Rmd](https://github.com/lusiki/WebMultiVar/blob/main/Predavanja/09_SURV.Rmd) 
<br>
**Čitanje:** [Prošlogodišnje predavanje](https://rpubs.com/shichich/610311) + []() + []()
<br>
<br>
### Predavanje 10: Analiza vremenskih serija



### Predavanje 11: Strojno učenje



### Predavanje 12: Analiza teksta



### Predavanje 13: Network analiza


